services:
  sma-discovery-service:
    build: ./discovery-client
    container_name: sma-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
  sma-configuration-service:
    build: ./configuration-service
    container_name: sma-configuration-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      sma-discovery-service:
        condition: service_healthy
  sma-garage-service:
    build: ./garage-service
    container_name: sma-garage-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sma-configuration-service:9999
    depends_on:
      sma-configuration-service:
        condition: service_healthy
  sma-client-service:
    build: ./client-service
    container_name: sma-client-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sma-configuration-service:9999
    depends_on:
      sma-configuration-service:
        condition: service_healthy
  sma-vehicule-service:
    build: ./vehicule-service
    container_name: sma-vehicule-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sma-configuration-service:9999
    depends_on:
      sma-client-service:
        condition: service_healthy
  sma-document-service:
    build: ./document-service
    container_name: sma-document-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sma-configuration-service:9999
    depends_on:
      sma-vehicule-service:
        condition: service_healthy
  sma-gateway-service:
    build: ./gateway-service
    container_name: sma-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://sma-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://sma-configuration-service:9999
    depends_on:
      sma-configuration-service:
        condition: service_healthy
  angular-frontend:
    build: angular-frontend
    container_name: angular-frontend
    ports:
      - '80:80'
    expose:
      - '80'
  thymeleaf-frontend:
    build: thymeleaf-frontend
    container_name: thymeleaf-frontend
    ports:
      - '8091:8091'
    expose:
      - '8091'
    environment:
      - KEYCLOAK_ISSUER_URL:http://localhost:8080/realms/sma-realm
      - KEYCLOAK_JWT_URL:http://localhost:8080/realms/sma-realm/protocol/openid-connect/certs

